#! /bin/bash

TO_KILL=`adb shell ps > /tmp/ps && cat /tmp/ps | fzf`
PID=`echo $TO_KILL | awk '{print $2}'`
NAME=`echo $TO_KILL | awk '{print $5}'`
if [ x"$PID" != x ] && [ x"$PID" != xPID ]
then
    adb shell kill -9 $PID && echo "$NAME is killed..."
fi
