#! /bin/bash
URL=`git remote -v | grep '(push)' | awk '{print $2}'`
PROJECT=${URL##*9418/}
echo PROJECT=$PROJECT
if [[ $1 == "" ]]
then
repo upload $PROJECT --re=taojinjing@huaqin.com
else
repo upload $PROJECT -D $1
fi

